# version: "3.9"

# services:
#   postgres:
#     image: postgres
#     restart: always
#     shm_size: 128mb
#     environment:
#       POSTGRES_USER: "dogker_admin"
#       POSTGRES_PASSWORD: "endeavor"
#       POSTGRES_DB: "billing_db"
#     ports:
#       - 5433:5433

#   pg-admin:
#     image: dpage/pgadmin4
#     environment:
#       - PGADMIN_DEFAULT_EMAIL=admin@dogker.com
#       - PGADMIN_DEFAULT_PASSWORD=dogkeradmin
#       - PGADMIN_LISTEN_PORT=5050
#     ports:
#       - 5051:5051
