// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateCharge(ctx context.Context, arg CreateChargeParams) (ChargesTable, error)
	CreateDeposit(ctx context.Context, arg CreateDepositParams) (DepositsTable, error)
	CreateMutation(ctx context.Context, arg CreateMutationParams) (MutationsTable, error)
	DeleteCharge(ctx context.Context, id uuid.UUID) error
	DeleteDeposit(ctx context.Context, id uuid.UUID) error
	DeleteMutation(ctx context.Context, id uuid.UUID) error
	GetCharge(ctx context.Context, id uuid.UUID) (ChargesTable, error)
	GetDeposit(ctx context.Context, id uuid.UUID) (DepositsTable, error)
	GetMutation(ctx context.Context, id uuid.UUID) (MutationsTable, error)
	ListCharges(ctx context.Context, arg ListChargesParams) ([]ChargesTable, error)
	ListDeposits(ctx context.Context, arg ListDepositsParams) ([]DepositsTable, error)
	ListMutations(ctx context.Context, arg ListMutationsParams) ([]MutationsTable, error)
	UpdateCharge(ctx context.Context, arg UpdateChargeParams) (ChargesTable, error)
	UpdateDeposit(ctx context.Context, arg UpdateDepositParams) (DepositsTable, error)
	UpdateMutation(ctx context.Context, arg UpdateMutationParams) (MutationsTable, error)
}

var _ Querier = (*Queries)(nil)
